{{- if .Values.stratus.ogcpersistentVolume.host }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-stratus-ogc
  labels:
    type: {{ .Values.stratus.ogcpersistentVolume.type | default "efs" }}
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  #nfs:
  #  server: {{ .Values.stratus.persistentVolume.host }} 
  #  path: {{ .Values.stratus.persistentVolume.path | default "/" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.stratus.ogcpersistentVolume.host }}
    volumeAttributes:
      path: {{ .Values.stratus.ogcpersistentVolume.path | default "/" }}
{{- end }}
---
{{- if .Values.stratus.ogcpersistentVolume.host }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-stratus-ogc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
{{- end }}
---
{{- if .Values.stratus.ui.enabled }}
{{- if .Values.stratus.uipersistentVolume.host }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-stratus-ui
  labels:
    type: {{ .Values.stratus.uipersistentVolume.type | default "efs" }}
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  #nfs:
  #  server: {{ .Values.stratus.persistentVolume.host }} 
  #  path: {{ .Values.stratus.persistentVolume.path | default "/" }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.stratus.uipersistentVolume.host }}
    volumeAttributes:
      path: {{ .Values.stratus.uipersistentVolume.path | default "/" }}
{{- end }}
---
{{- if .Values.stratus.uipersistentVolume.host }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-stratus-ui
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
{{- end }}
{{- end }}
