apiVersion: v1
kind: Service
metadata:
  namespace: ec
  labels:
    name: redis-proxy
    role: proxy
  name: redis-proxy
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    name: redis
