redis:
  implementation: "lettuce"
  # sentinel, cluster, or manual
  type: "sentinel"

  # only for sentinel
  sentinel:
    minReplicas: 1
    maxReplicas: 3
  cache:
    enabled: "true"
    parallel: "true"

stratus:
  ogc:
    container:
      repo: "docker.io/gsstratus"
      image: "stratus-ogc"
      tag: "1.0.2"
    resources:
      minReplicas: 1
      maxReplicas: 3
      mem: 1.0
      maxMem: 4.0
      cpu: "500m"
      maxCpu: 4.0
  ui:
    enabled: "false"
    container:
      repo: "docker.io/gsstratus"
      image: "stratus-ui"
      tag: "1.0.2"
    resources:
      minReplicas: 1
      maxReplicas: 1
      mem: 1.0
      maxMem: 4.0
      cpu: "500m"
      maxCpu: 4.0
  debug: "false"
  gwc:
    enabled: "false"

